name: Update WordPress.org Assets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'
      - 'readme.txt'

jobs:
  asset-update:
    name: Update plugin assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update WordPress.org assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: jazzs3quence-priority-manager-for-ai-connectors
